module: MetovaAnalytics
github_url: https://github.com/metova/MetovaAnalytics
clean: true
theme: fullwidth
xcodebuild_arguments: [-workspace, MetovaAnalytics.xcworkspace, -scheme, MetovaAnalytics]
output: docs
